//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par xsd, Version=4.0.30319.17929.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace XfdServer {
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class Projects {
        
        private ProjectsProject[] projectField;
        
        private ProjectsIterationConfig[] configField;
        
        /// <remarks/>
        [XmlElement("Project")]
        public ProjectsProject[] Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("IterationConfig", IsNullable=false)]
        public ProjectsIterationConfig[] Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class ProjectsProject {
        
        private ProjectsProjectBuildConfiguration[] buildConfigurationsField;
        
        private string nameField;
        
        /// <remarks/>
        [XmlArrayItem("BuildConfiguration", IsNullable=false)]
        public ProjectsProjectBuildConfiguration[] BuildConfigurations {
            get {
                return this.buildConfigurationsField;
            }
            set {
                this.buildConfigurationsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class ProjectsProjectBuildConfiguration {
        
        private string nameField;
        
        private string shortNameField;
        
        private criticityLevel criticityField;
        
        private bool showTestCountField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string shortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public criticityLevel criticity {
            get {
                return this.criticityField;
            }
            set {
                this.criticityField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public bool showTestCount {
            get {
                return this.showTestCountField;
            }
            set {
                this.showTestCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [Serializable()]
    public enum criticityLevel {
        
        /// <remarks/>
        low,
        
        /// <remarks/>
        medium,
        
        /// <remarks/>
        high,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true)]
    public partial class ProjectsIterationConfig {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
